  GET http://localhost:8080/contacts

# ##get one contact

# GET https://cse341-4jz0.onrender.com

#create contact

# POST http://localhost:8080/contacts HTTP/1.1 
# content-type: application/json

# {
#     "firstName":"Coleton", 
#     "lastName":"Peterson", 
#     "email":"copeterson@email.com", 
#     "faveColor":"Blue", 
#     "birthdate":"07/02/1995"
# }

# PUT http://localhost:8080/contacts/66496976bc9e1b56044ab024 HTTP/1.1 
# content-type: application/json

# {
#     "firstName":"Coleton", 
#     "lastName":"Peterson", 
#     "email":"cpeterson@314.com", 
#     "faveColor":"Blue", 
#     "birthdate":"07/02/1995"
# }

DELETE http://localhost:8080/contacts/66496976bc9e1b56044ab024 HTTP/1.1 
content-type: application/json

# http://localhost:8080/api-docs

# POST https://cse341-4jz0.onrender.com
# HTTP/1.1 
# content-type: application/json

# {
#     "firstName":"Coleton", 
#     "lastName":"Peterson", 
#     "email":"copeterson@email.com", 
#     "faveColor":"Blue", 
#     "birthdate":"07/02/1995"
# }

# PUT https://cse341-4jz0.onrender.com/664038dbc38137b31fa879f0
# content-type: application/json

# {
#     "firstName":"Coleton", 
#     "lastName":"Peterson", 
#     "email":"cpeterson@314.com", 
#     "faveColor":"Blue", 
#     "birthdate":"07/02/1995"
# }

# DELETE https://cse341-4jz0.onrender.com/contacts/66403a06c38137b31fa879f1 HTTP/1.1 
# content-type: application/json

# https://cse341-4jz0.onrender.com/api-docs